/*
 * Define a bunch of functions of the type get_available_extensions, get_available_blend_modes, ...
 * Define a bunch of functions of the type is_extension_supported, is_blend_mode_supported, ...
 */
